{% set name = "owa-cli" %}
{% set version = "0.3.9.post1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/owa_cli-{{ version }}.tar.gz
  sha256: ad0720eb1f145f00d182df79e57f6ecac6db84c2f0f4945b2a615f3345eb3e5f

build:
  entry_points:
    - owl = owa.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - loguru >=0.7.3
    - mcap-owa-support
    - orjson >=3.10.15
    - owa-core
    - packaging >=25.0
    - plotext >=5.3.2
    - pydantic >=2.10.6
    - requests >=2.32.3
    - tqdm >=4.67.1
    - typer >=0.15.1

test:
  imports:
    - owa.cli
  commands:
    - pip check
    - owl --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: "Everything you need to build state-of-the-art foundation multimodal desktop agent, end-to-end."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
